// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Express = require("bs-express/src/Express.js");

console.log("hello");

var app = Express.express(/* () */0);

exports.app = app;
/*  Not a pure module */
